# Generated by Django 4.0.1 on 2022-01-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='list_items',
        ),
        migrations.AddField(
            model_name='feature',
            name='list_items',
            field=models.ManyToManyField(to='web.FeatureList'),
        ),
    ]
