# Generated by Django 4.0.1 on 2022-01-19 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_pricing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='feature_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='not_feature_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
    ]
