# Generated by Django 4.0.1 on 2022-01-19 18:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_pricing_feature_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='feature_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='not_feature_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
