# Generated by Django 4.0.1 on 2022-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_pricing_feature_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('interested_in', models.CharField(choices=[('1', 'Marketing'), ('2', 'Sales'), ('3', 'Designing')], max_length=128)),
                ('user_agreement', models.BooleanField()),
            ],
        ),
    ]
